[workspace]
resolver = "3"
members = [
    "console",
    "gateway",
    "access",
    "lib/logging",
    "lib/aiway-plugin",
    "lib/aiway-protocol",
    "test-server",
    "lib/loadbalance",
    "lib/cache",
    "aiway",
    "logg",
    "lib/alert",
    "lib/plugin-manager",
    "lib/busi",
    "lib/certs"
]
