name: Check

on:
  push:
    branches: [master]
    paths-ignore:
      - "docs/**"
      - "*.md"
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Run cargo check
        run: cargo check --workspace --exclude aiway
